### ISSUE TITLE
실시간 유류비 계산을 위한 전국 주유소 유가 평균정보 API 도입

### ISSUE THREAD

**Issue by kimsehwan96** [kimsehwan96/car-iot-platform-from-kpu#100]
<img width="1260" alt="스크린샷 2021-04-12 오후 9 28 30" src="https://user-images.githubusercontent.com/59886140/114394328-0b4f8700-9bd6-11eb-9446-7f8d279cf50d.png">

@kwhong95 

오피넷이라는 곳에서 유가 정보 관련한 API를 호출 할 수 있습니다.

무료버전 API는 일 1500건 무료 호출이 가능하므로, 기기 최초 가동시 1번 호출하는것을 가정했을 때 졸업작품 내에서는 한도를 초과하지 않겠습니다.

이 API는 greengrass 람다 (라즈베리파이 디바이스 내에서 돌아가는 코드)에서 호출할 예정이며, 프론트에서 소비 가능하게끔 localhost로 호출 가능한 API 엔드포인트를 제공하겠습니다. 

<img width="1260" alt="스크린샷 2021-04-12 오후 9 30 26" src="https://user-images.githubusercontent.com/59886140/114394568-4f428c00-9bd6-11eb-9ad0-1e46feaac650.png">

**Comment by kwhong95** [comment]
확실히 활용성 있는 데이터네요

실시간 대시보드 연료 파트에 활용할

생각이신가요??

**Comment by kimsehwan96** [comment]
넵 연료파트에서 활용할 예정이며, 프론트에서도 간단히 오늘의 평균 유가 정보 보여줄때 활용 할 수 있을 것 같아요.

라즈베리파이 내부에서는 실시간 유류비 계산에 활용할 예정이에요. 

(실시간 유류비 계산은 프론트에서 하지 않고 라즈베리파이 내부적으로 하는걸로)

**Comment by kwhong95** [comment]
오오 네 알겠습니다~

다음 회의때 내용 추가 회의 때 상세히 공유해주시면 감사하겠습니다!!
