### ISSUE TITLE
submodule 관련 문의

### ISSUE THREAD

**Issue by DPS0340** [kimsehwan96/car-iot-platform-from-kpu#112]
안녕하세요 세환님 :)
다름이 아니라, 이 레포를 쭉 훑어보려고 하는데 private 처리? 된 submodule이 있는데, 이 모듈이 프로젝트 구조 내부에서 중요한 위치를 차지할까요?
만약 그렇다면, 서브모듈 레포를 볼 수 있는 방법이 있을까요?

레포 url은 다음과 같습니다.
https://github.com/kwhong95/kpu_sp_rt_dashboard/

감사합니다!!

**Comment by kimsehwan96** [comment]
@DPS0340 안녕하세요 지호님. 

해당 레포 URL에 있던 내용은 아래 URL에 있는 내용과 동일합니다.

https://github.com/kimsehwan96/kpu_sp_rt_dashboard

다만, cloud_realtime_dashboard 에 해당하는 서브모듈이 위 링크구요,

realtime_dashboard  에 해당하는 서브모듈은, 

위 링크에서 특정 커밋을 참고하시면 됩니다. (https://github.com/kimsehwan96/kpu_sp_rt_dashboard/commit/ce53890980d63330335e79ed6d61f17b96fa113e)


즉 하나의 커밋 사이로 cloud_realtime_dashboard 와, realtime_dashboard 코드가 거의 대부분 동일합니다.

이상적인 프로젝트였다면, 실행하는 환경이 로컬인지, 클라우드인지에 따라 분기처리를 했어야 했을탠데요. 졸업작품 기간 및 난이도 상 그렇게 처리하지 않고 분리해버렸습니다 :)

**Comment by kimsehwan96** [comment]
제가 위쪽에 드린 링크는, 클라우드에 호스팅되는 버전입니다. git diff를 따라가보시면 로컬버전을 -> 클라우드에서 사용 가능하도록 수정한 내용 확인 가능할거에요. 

해당 커밋도 링크 드립니다. https://github.com/kimsehwan96/kpu_sp_rt_dashboard/commit/e2e313b43bf69857976b6f5b4acf6811c36ad287

**Comment by DPS0340** [comment]
명쾌하게 알려주셔서 감사합니다 ㅎㅎㅎㅎ
